In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('ChicagoNarcoCrimes_2001_to_2017_final.csv')

In [5]:
data = data.rename(columns={'X Coordinate': 'X_Coordinate', 'Y Coordinate': 'Y_Coordinate'})

In [6]:
data

,Drug,District,X_Coordinate,Y_Coordinate,Year,Latitude,Longitude
0,Cannabis,19,1164839.0,1930205.0,2002,41.964093,-87.669321
1,Cannabis,6,1169813.0,1848186.0,2006,41.738918,-87.653420
2,Cannabis,22,1174313.0,1830380.0,2004,41.689957,-87.637461
3,Cannabis,5,1176839.0,1834173.0,2005,41.700310,-87.628099
4,Cannabis,6,1164407.0,1852089.0,2009,41.749744,-87.673117
...,...,...,...,...,...,...,...
6096,Cannabis,4,1185612.0,1851831.0,2013,41.748564,-87.595422
6097,Cannabis,18,1171234.0,1908233.0,2005,41.903662,-87.646455
6098,Cannabis,2,1178540.0,1868423.0,2015,41.794257,-87.620832
6099,Heroin,15,1141002.0,1901182.0,2005,41.884924,-87.757679
6100,Heroin,10,1149267.0,1893417.0,2012,41.863460,-87.727530

In [7]:
data.to_csv('data.csv')

In [8]:
df = data.head(10)

In [9]:
df

       Drug  District  X_Coordinate  Y_Coordinate  Year   Latitude  Longitude
0  Cannabis        19     1164839.0     1930205.0  2002  41.964093 -87.669321
1  Cannabis         6     1169813.0     1848186.0  2006  41.738918 -87.653420
2  Cannabis        22     1174313.0     1830380.0  2004  41.689957 -87.637461
3  Cannabis         5     1176839.0     1834173.0  2005  41.700310 -87.628099
4  Cannabis         6     1164407.0     1852089.0  2009  41.749744 -87.673117
5    Heroin        15     1143388.0     1904517.0  2003  41.894031 -87.748834
6   Cocaine         8     1155414.0     1864857.0  2010  41.784966 -87.705730
7     Crack        18     1172774.0     1906610.0  2006  41.899175 -87.640847
8    Heroin        15     1141343.0     1902645.0  2006  41.888932 -87.756391
9  Cannabis         3     1182456.0     1860755.0  2011  41.773126 -87.606710

In [ ]:
df.to_csv('test.csv')